####################################
## My Bash Profile 'bash_profile'
####################################

## OLD single file load if it exists
if [ -f ~/.bashrc ]
	then source ~/.bashrc
fi

## Autocorect typos in path name when using 'cd'
shopt -s cdspell;

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function* 

## ls on directory change (cd) TEST
cd () { builtin cd "$@" && ls; }
